package com.companion.awareness

/**
 * Curated interest taxonomy used to seed the Profile editor. ~150
 * tags across 20 categories, actionable enough for the LLM to match
 * on real on-screen content. English labels so the matcher works on
 * any language content.
 *
 * The user can also type free-form tags — these are just a starting
 * menu.
 */
object InterestsCatalog {
    val CATEGORIES: Map<String, List<String>> = linkedMapOf(
        "Software Development" to listOf(
            "Rust programming",
            "Kotlin programming",
            "Python programming",
            "TypeScript programming",
            "Go programming",
            "Android development",
            "iOS development",
            "Web development",
            "Backend architecture",
            "Database design",
            "DevOps and CI/CD",
            "Open source projects",
        ),
        "AI and Data" to listOf(
            "Large language models",
            "AI coding tools",
            "Machine learning research",
            "Prompt engineering",
            "Local AI models",
            "AI ethics and policy",
            "Data engineering",
            "Computer vision",
            "AI startups",
        ),
        "Technology Industry" to listOf(
            "Tech layoffs",
            "Startup funding rounds",
            "Big Tech news",
            "Cybersecurity breaches",
            "Privacy and surveillance",
            "Hardware releases",
            "Developer tools",
            "Cloud platforms",
        ),
        "Career and Work" to listOf(
            "Remote work opportunities",
            "Salary negotiation",
            "Job interviews",
            "Freelancing and contracting",
            "Tech hiring trends",
            "Career transitions",
            "Management and leadership",
            "Productivity systems",
            "Portugal tech jobs",
        ),
        "Personal Finance" to listOf(
            "Stock market news",
            "Index fund investing",
            "Cryptocurrency markets",
            "Real estate investing",
            "Tax optimization",
            "Personal budgeting",
            "Retirement planning",
            "Portugal taxes and NHR",
            "Mortgage rates",
        ),
        "Business and Economy" to listOf(
            "European economy",
            "Portuguese economy",
            "Central bank decisions",
            "Inflation and rates",
            "Mergers and acquisitions",
            "Entrepreneurship",
            "Small business tips",
        ),
        "Health and Fitness" to listOf(
            "Strength training",
            "Running and marathons",
            "Nutrition science",
            "Sleep optimization",
            "Mental health",
            "Meditation and mindfulness",
            "Longevity research",
            "Home workouts",
            "Injury recovery",
        ),
        "Food and Cooking" to listOf(
            "Home cooking recipes",
            "Portuguese cuisine",
            "Mediterranean diet",
            "Baking and bread",
            "Wine and port",
            "Coffee and espresso",
            "Restaurant reviews",
            "Meal prep",
        ),
        "Travel" to listOf(
            "Europe travel deals",
            "Weekend trips Portugal",
            "Digital nomad destinations",
            "Flight deals",
            "Hiking and nature travel",
            "City guides",
            "Travel hacking and miles",
        ),
        "Sports" to listOf(
            "Football Primeira Liga",
            "Champions League",
            "Formula 1",
            "NBA basketball",
            "Tennis Grand Slams",
            "Cycling Tour de France",
            "MMA and UFC",
            "Olympic sports",
            "Portugal national team",
        ),
        "News and Current Affairs" to listOf(
            "Portuguese politics",
            "European Union policy",
            "US politics",
            "Geopolitics and conflicts",
            "Climate policy",
            "Immigration policy",
            "Housing crisis Portugal",
            "Local Lisbon news",
            "Local Porto news",
        ),
        "Science" to listOf(
            "Space exploration",
            "Physics discoveries",
            "Biotechnology",
            "Neuroscience",
            "Climate science",
            "Renewable energy",
            "Archaeology finds",
            "Scientific papers",
        ),
        "Learning and Education" to listOf(
            "Online courses",
            "Language learning",
            "Book recommendations",
            "Academic research",
            "Study techniques",
            "Certifications and exams",
        ),
        "Creative and Arts" to listOf(
            "Photography techniques",
            "Digital illustration",
            "Music production",
            "Writing and blogging",
            "Video editing",
            "Graphic design",
            "3D modeling",
        ),
        "Entertainment" to listOf(
            "Movie releases",
            "TV series reviews",
            "Streaming platforms",
            "Anime and manga",
            "Celebrity news",
            "Film festivals",
            "Standup comedy",
        ),
        "Gaming" to listOf(
            "PC gaming news",
            "Indie game releases",
            "PlayStation games",
            "Nintendo Switch games",
            "Game development",
            "Esports tournaments",
            "Board games",
            "Tabletop RPGs",
        ),
        "Hobbies and Lifestyle" to listOf(
            "DIY home projects",
            "Gardening",
            "Woodworking",
            "Watches and EDC",
            "Fashion and style",
            "Minimalism",
            "Pets and dog training",
            "Puzzles and chess",
        ),
        "Relationships and Family" to listOf(
            "Dating and relationships",
            "Parenting tips",
            "Social skills",
            "Communication skills",
            "Friendship and community",
        ),
        "Mind and Philosophy" to listOf(
            "Stoicism",
            "Psychology and behavior",
            "Habits and self improvement",
            "Philosophy and ethics",
            "Spirituality and religion",
            "Journaling",
        ),
        "Cars and Transport" to listOf(
            "Electric vehicles",
            "Car reviews",
            "Public transport Portugal",
            "Cycling infrastructure",
            "Road trips and motoring",
        ),
    )

    /** Flat list used by the autocomplete filter. */
    val ALL: List<String> = CATEGORIES.values.flatten()
}
